### ISSUE TITLE
[RPI] Video Resolution changing on video playback

### ISSUE THREAD

**Issue by bairdy** [xbianonpi/xbian#674] opened 2015-02-12 00:01 UTC
on video playback since Kodi 14.1 Git:2015-02-05-38e4046-dirty it changes the resolution before playing a video file and makes the kodi overlay look blurry and knocking the aspect ratio out on the video had been fine on xbmc_14.0-1419750242

on checking the log on loading videos its adjusting the video output
```23:24:45 T:2667574288  NOTICE: Display resolution ADJUST : 640x480 (640x480) @ 72.00 - Full Screen (32) (weight: 0.001)```
but the video has a resolution of 720x404 and on a differant video it adjusts as follows

```23:28:44 T:2909250576  NOTICE: Display resolution ADJUST : 1024x768 (1024x768) @ 59.94 - Full Screen (39) (weight: 0.000)```
and the videos resolution is 1280x536

a full log is available at http://xbmclogs.com/show.php?id=423750

**Comment by anaconda** [comment] 2015-02-12 02:01
This should have been fixed - fix will be in next update. Can you add this to your advancedsettings.xml and report whether I have identified the cause correctly (Kodi needs a restart):
```
<video>
  <adjustdisplayrestomatchvideo>false</adjustdisplayrestomatchvideo>
</video>
```
If a `<video>` sections exists already, add it there.

**Comment by bairdy** [comment] 2015-02-12 09:37
@anaconda  
that does the job and fixes it

**Closed** 2015-02-12 13:20 UTC
Labels: Raspberry Pi
